### ISSUE TITLE
Update content on <Digital Infrastructure Incubator Project Page>

### ISSUE THREAD

**Issue by rayelz** [digitalinfrastructurefund/website#17]
**URL**
https://difund.herokuapp.com/projects/digital-infrastrcuture-incubator

**Content to be modified**

- We'd love it if this page would link to the Incubator site (https://incubator.codeforscience.org)
- Can we change the title description from [Supporting projects to implement research-informed best practices at the time of need on governance, sustainability, and inclusion] to: [**Supporting open source project leaders implementing best practices in sustainability, governance, and community health**]
- Can we change the subtitle from [Code for Science & Society is building an expert-advised cohort program for open digital infrastructure projects who wish to implement research-based recommendations relating to three common challenges faced by digital infrastructure projects: governance, sustainability, and community health.] to [**Code for Science & Society's cohort program is designed to amplify the impact of research-based recommendations by providing tailored support for open source project leaders as they iterate solutions around a single sociotechnical challenge.**]
- Danielle Robinson is ED of Code for Science & Society, the other team members listed (Ruben and Talan) are not ours
- We'd love to add Rayya El Zein (Program Manager, Digital Infrastructure Incubator) as another team member for this project

thank you!

**Comment by RichardLitt** [comment]
Done!
