### ISSUE TITLE
Rethink resources page

### ISSUE THREAD

**Issue by BenJam** [digitalinfrastructurefund/website#25]
The resources page is already a little unruly: https://digitalinfrastructure.fund/resources/

We should probably rethink the indexing and findability here. One of the key requirements from Sloan's side was a single place to gather all the research in this space for easy browsing and retrieval. Ford broke things up by project https://www.fordfoundation.org/campaigns/critical-digital-infrastructure-research/  which works well, but we may also want to indicate new research too.

/cc @Memo-Es @flickz

**Comment by Memo-Es** [comment]
@BenJam we can implement a basic search + filters for the resources page 
<img width="1504" alt="Screen Shot on 2022-01-11 at 21-17-10" src="https://user-images.githubusercontent.com/49539954/149058021-53ff2e6d-ae42-41fd-b317-a54ce44af1a1.png">

**Comment by RichardLitt** [comment]
@Memo-Es That sounds good to me. How do we start?

**Comment by Memo-Es** [comment]
The design is ready [here](https://www.figma.com/file/omAmFnZDmHFfWPxqOQqp4a/Digital-Infrastructure-Fund---Website?node-id=117%3A33287).
An engineer needs to implement it, I don't know if we still rely on @flickz on this
@RichardLitt

**Comment by RichardLitt** [comment]
I've asked on Slack.

**Comment by flickz** [comment]
@RichardLitt What are the types expected in the "Type" selection?
