### ISSUE TITLE
Footer links not present

### ISSUE THREAD

**Issue by BenJam** [digitalinfrastructurefund/website#26]
![Screenshot 2022-01-11 at 14 24 22](https://user-images.githubusercontent.com/158833/148960657-26bdec2f-227f-4158-97a9-8549f0230e52.png)

not one of the links in the footer is present

- podcast
- twitter
- slack
- Open Collective link
- Design docs (figma)

**Comment by RichardLitt** [comment]
Mostly done - looking for the design link, now.
